# Generated by Django 5.0.7 on 2024-07-16 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile_no', models.PositiveIntegerField()),
                ('vill_town', models.CharField(max_length=200)),
                ('post_office', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('permanent_address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=200)),
                ('pin', models.PositiveIntegerField()),
                ('student_photo', models.ImageField(upload_to='media/profile_pic')),
                ('dob_certificate', models.FileField(upload_to='media/students/certificates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.class')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.session')),
            ],
        ),
    ]
