# Generated by Django 5.0.7 on 2024-07-17 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile_no', models.PositiveIntegerField()),
                ('pan_no', models.CharField(max_length=10)),
                ('aadhaar_no', models.PositiveBigIntegerField()),
                ('vill_town', models.CharField(max_length=200)),
                ('post_office', models.CharField(max_length=200)),
                ('police_station', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pin', models.PositiveIntegerField()),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('twelfth_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('qualification', models.CharField(max_length=500)),
                ('bank_name', models.CharField(max_length=350)),
                ('account_no', models.PositiveIntegerField()),
                ('branch_name', models.CharField(max_length=350)),
                ('ifsc', models.CharField(max_length=100)),
                ('teacher_photo', models.ImageField(upload_to='media/profile_pic')),
                ('cv_resume', models.FileField(upload_to='media/teachers/cv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
