# Generated by Django 5.0.7 on 2024-07-17 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='aadhaar_no',
            new_name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='pan_no',
        ),
        migrations.AddField(
            model_name='teacher',
            name='account_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='pan_number',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='permanent_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
