# Generated by Django 5.0.7 on 2024-08-04 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_teacherattendance_delete_teacher_attendance'),
        ('home', '0004_alter_class_session_alter_subject_class_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.BooleanField(default=False)),
                ('deadline_date_time', models.DateTimeField()),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image')], default='text', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assignments/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacherallotment')),
            ],
        ),
    ]
