# Generated by Django 5.0.7 on 2024-08-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_assignments'),
        ('home', '0004_alter_class_session_alter_subject_class_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Assignment',
        ),
    ]
