# Generated by Django 5.0.7 on 2024-07-25 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_teacherattendance_delete_teacher_attendance'),
        ('home', '0003_rename_session_id_class_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksheet', models.FileField(upload_to='marksheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
        ),
    ]
