# Generated by Django 5.0.7 on 2024-07-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_class_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='session_id',
            new_name='session',
        ),
    ]
