# Generated by Django 5.0.7 on 2024-07-27 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_teacherattendance_delete_teacher_attendance'),
        ('home', '0003_rename_session_id_class_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.session'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.class'),
        ),
        migrations.CreateModel(
            name='TeacherAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.teacher')),
            ],
        ),
    ]
