# Generated by Django 5.0.7 on 2024-07-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_teacherattendance_delete_teacher_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('image', 'Image')], default='text', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='notifications/files/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/images/')),
                ('confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(to='academics.teacher')),
            ],
        ),
    ]
