# Generated by Django 5.0.7 on 2024-07-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_leaveapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='applicant',
            new_name='applicant_id',
        ),
    ]
