# Generated by Django 5.0.7 on 2024-07-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_studentnotification_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Declined', 'Declined'), ('Approved', 'Approved'), ('Requested', 'Requested')], default='Requested', max_length=10),
        ),
    ]
